#!/bin/bash

source ./apply.sh

config_path=$1

config=$(cat $config_path)

commit_message="converge common-header"

for row in $(echo $config | jq -r '.[] | @base64'); do
	row=$(echo $row | base64 --decode)
	remote=$(echo $row | jq -r '.Remote')
	config=$row
  apply "$remote" "$config" "$commit_message"
done
